name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: the-orrery/.github/.github/workflows/python-ci.yml@62bfc4a14ab28fc932919f6d2d350f465b188494 # v12
    with:
      ruff-extend-ignore: "['TRY003','RUF001']"
      ruff-extend-per-file-ignores: "{'tests/**'=['ARG']}"
