name: CI
on: [push, pull_request]
jobs:
  ci:
    uses: the-orrery/.github/.github/workflows/python-ci.yml@v6
    with:
      ruff-extend-ignore: "['TRY003']"
      ruff-extend-per-file-ignores: "{'tests/**'=['ARG']}"
